### PR TITLE
Polygon Inner rings orientation

### PR DESCRIPTION
**Pull request by Montago**
This change orients inner rings (holes) in polygons correctly (CCW)

### CODE REVIEW

**Comment by arthur-e** [comment]
This fixed the problem for Polygons but not for MultiPolygons. The (new) example of a MultiPolygons with a hole from Wikipedia still does not render correctly.

```
MULTIPOLYGON (((40 40, 20 45, 45 30, 40 40)), ((20 35, 10 30, 10 10, 30 5, 45 20, 20 35), (30 20, 20 15, 20 25, 30 20)))
```

**Comment by arthur-e** [comment]
There is one small change to get this to work for MultiPolygons; you have to check for the Polygon type.

```
// Orient inner rings correctly
if (polygonIsClockwise(c[j]) && this.type == 'polygon') {
  verts.reverse();
}
```

**Comment by arthur-e** [comment]
The `deconstruct()` method in `wicket-gmaps3.js` needs the same kind of fix, but the code is more complicated. One of the things that needs to be fixed is the determination of `multiFlag`; the determination of whether or not a `google.maps.Polygon` instance is a Polygon or MultiPolygon.

**Comment by Montago** [comment]
It should be very easy to find out if Google maps contain multi polygons or not by looking at the direction they are made..  eg, if two polygons are CW => multi 
If one polygon is CW and the rest are CCW, then its a polygon with holes

**Pull request merged**
