### PR TITLE
wicket-leaflet: add module loader support

### PR DESCRIPTION
**Pull request by mpschaeuble**

### CODE REVIEW

**Comment by arthur-e** [comment]
We have no tests for the Leaflet extension. Can you confirm that the [standard WKT test cases](https://github.com/arthur-e/Wicket/blob/master/tests/wicket-spec.js#L27) work under these changes? Thanks!

**Comment by mpschaeuble** [comment]
No, doesn't work at all. A simple toObject() fails because an object with the interface {x: number, y: number} is passed to leaflets coordsToLatLng method, which expects a coordinate to be passed a as a two element array. But this issue is not related to this pull request.

I would assume that at least the leaflet part is completely broken. It would probably be best to have a proper automated test setup for each map provider.

**Comment by arthur-e** [comment]
Maybe I'm not following what's changed in this pull request. The intent with the library-specific extension files:

```
wicket-leaflet.js
wicket-gmap3.js
wicket-arcgis.js
```

...Is that they each take care of the translating Wicket's (`wicket.js`) **internal** representation of spatial coordinates (which, as you pointed out, are stored as objects, `{x: number, y: number}`) into the library-specific object. For instance, I believe that the Leaflet extension `wicket-leaflet.js` does (or did, at one point) transform`{x: number, y: number}` into a `[x, y]` array, prior to passing it to the respective Leaflet geometry constructor.

We also do have a specific set of tests for one of the map providers, Google Maps, in the following spec:

```
tests/wicket-gmap3-spec.js
```

These are difficult to automate (I currently don't know how) because they require loading external resources in a (headless?) browser. Hence, the Google Maps tests above are not automated. Would love it if someone could find a way to automate them for all providers.

**Comment by arthur-e** [comment]
Yes, I believe `coordsToLatLng()` is based on the previous major version of Leaflet and things have changed a lot. See #103 #104 and #119. Hopefully someone will issue a Pull Request with a patch for these issue(s).

**Comment by nickescallon** [comment]
@arthur-e - I think this PR should do the trick: https://github.com/arthur-e/Wicket/pull/126

**Pull request merged**
